---
development:
  cloud_name: ds5nimk7q
  api_key: '834768218516859'
  api_secret: 8bG_vgTHBRsHjxbldtwa_-JStgY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ds5nimk7q
  api_key: '834768218516859'
  api_secret: 8bG_vgTHBRsHjxbldtwa_-JStgY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ds5nimk7q
  api_key: '834768218516859'
  api_secret: 8bG_vgTHBRsHjxbldtwa_-JStgY
  enhance_image_tag: true
  static_image_support: false
