# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d519cc087c3bbc248d8c94203e714c28f4dfc9abaf88ae7a2f47260bc8ee558fede43feef53853a4629fea548609d32b382d83f22f606b26154528bd2eac92f1

test:
  secret_key_base: 3862e5227e020d05a4600d0f0252788f7bc2708b6bf2e76a3d4f94addd0d1d468e3f205d3addc5514cdfb92ca164b040efb7dc39bf4d2eda80123a5497e6b4b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
